version: '3.9'
services:
  drupal-server:
    container_name: drupal-server
    image: alpine
    build: .
    ports:
     - "8080:80"
    environment:
      sitename: webteam
      dbhost: mysql
      dbport: 3306
      dbuser: mysql
      dbpass: 1234
      dbname: drupal
      user: admin
      pass: 1234
      local_build: "true"
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    container_name: drupal-db
    image: mysql:5.7.39
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: drupal
    command: [--max-allowed-packet=67108864]
    healthcheck:
      test: "mysqladmin -umysql -p1234 ping"
      interval: 10s
      timeout: 5s
      retries: 30
    restart: always
