version: '2'
services:
  drupal-server:
    container_name: evs
    image: customcentdrupalserver
    ports:
     - "8084:80"
    environment:
      CONTAINER_BRANCH_OR_TAG: upgrade
      image_branch_or_tag: 1.1.17
      load_database: 1
      repository: "https://github.com/CBIIT/nci-evs"
      hash_salt: k_7ame-GnEyWUYWKFJWIL0EjcwIZnf6UjVvT3YNgTxM6Rb2qUWNP8pOzxQ_Q29OtENOVGzMnHA
      database: evs
      username: root
      password: my-secret-pw
      host: 192.168.0.170 
      port: 3308
      namespace: $namespace
      driver: mysql
      ldap_port: 636
      ldap_address: ldaps://nihdcadhub3.nih.gov

