version: '2'
services:
  drupal-server:
    container_name: drupal-server
    image: alpine
    build: .
    ports:
     - "8080:80"
    environment:
      sitename: webteam
      dbhost: 192.168.0.170
      dbport: 55002
      dbuser: mysql
      dbpass: 1234
      dbname: webteam
      user: admin
      pass: 1234

