version: '2'
services:
  drupal-server:
    container_name: events
    image: drupal-server
    network_mode: bridge
    external_links:
      - mysql57:db
    ports:
     - "8080:80"
    environment:
      hash_salt: paxwBNh8p2uVhxb0zRaLrB_vTsme3iG3rEeE1ABh9SxFhnkSmG56ezeqBeK995f
      database: events
      username: root
      password: my-secret-pw
      host: db
      port: 3308
      namespace:
      driver: mysql
